## Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

In [6]:
import numpy as np

arr = np.array([3,6,9])
arr * 2

array([ 6, 12, 18])

example when its valid 

In [57]:
a1 = np.random.randint(0,9,8)
a1 = a1.reshape(4,2)
print(a1,a1.shape ,'\n\n')

a2 = np.random.randint(0,9,2)
a2 = a2.reshape(1,2)
print(a2, a2.shape)

[[8 2]
 [5 2]
 [5 6]
 [7 6]] (4, 2) 


[[5 8]] (1, 2)


In [56]:
print(a1 + a2)

[[ 2 10]
 [ 4 13]
 [ 0  8]
 [ 4 15]]


Example when its not valid

In [58]:
a1 = np.random.randint(0,9,8)
a1 = a1.reshape(4,2)
print(a1,a1.shape ,'\n\n')

a2 = np.random.randint(0,9,2)
a2 = a2.reshape(2,1)
print(a2, a2.shape)

[[8 1]
 [7 2]
 [2 3]
 [8 1]] (4, 2) 


[[6]
 [0]] (2, 1)


In [59]:
print(a1 + a2)

ValueError: operands could not be broadcast together with shapes (4,2) (2,1) 