## Numpy Array

Comparison between np array and list

In [2]:
setup = "import numpy as np"
import timeit


c1='''
s=0
lst = [i for i in range(10000)]
for i in lst:
    s*=i
'''

c2='''
s=0
np_arr = np.arange(10000)
for i in np_arr:
    s*=i
'''

print (timeit.timeit(stmt = c1, number = 10000))
print (timeit.timeit(setup=setup,stmt = c2, number = 10000))



9.044506900000002
13.082854899999987


In [3]:
import numpy as np

# create a Python list and a NumPy array with 1 million elements
lst = [i for i in range(10000)]
arr = np.arange(10000)

# perform element-wise multiplication using a Python list
def multiply_list(lst):
    return [elem * 2 for elem in lst]

# perform element-wise multiplication using a NumPy array
def multiply_array(arr):
    return arr * 2

# time the list multiplication operation
list_time = timeit.timeit(lambda: multiply_list(lst), number=100)

# time the array multiplication operation
array_time = timeit.timeit(lambda: multiply_array(arr), number=100)

# print the results
print("List multiplication time:", list_time)
print("Array multiplication time:", array_time)

List multiplication time: 0.09058059999999557
Array multiplication time: 0.0009928000000059


In [4]:
# multi Dimensional
arr = np.array([[1,1],[2,2],[3,3]])
arr.shape

(3, 2)

In [5]:
# Converting  a generator into np array

l = (a*a for a in range(8))
print(type(l))
ar = np.fromiter(l,int)
ar

<class 'generator'>


array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [6]:
# converting simple list into nd array

l = [a*a for a in range(8)]
print(type(l))
ar = np.array(l)
ar

<class 'list'>


array([ 0,  1,  4,  9, 16, 25, 36, 49])

###### numpy.arange():
This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

In [7]:
a = np.arange(0,10 ,2,float)
a

array([0., 2., 4., 6., 8.])

In [30]:
np.ones([10000,100])

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [31]:
np.zeros([10000,100])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Operations

In [76]:
arr1 = np.arange(4, dtype = int)
arr1 = ar1.reshape(2,2)

print(ar1,'\n')

arr2 = np.arange(5,9)
arr2 = ar2.reshape(2,2)

print(ar2)

[[0 1]
 [2 3]] 

[[5 6]
 [7 8]]


In [78]:
print('\nAdding the two arrays:')
print(np.add(arr1, arr2))
 
print('\nSubtracting the two arrays:')
print(np.subtract(arr1, arr2))
 
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))
 
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))

print('\nApplying mod() function:')
print(np.mod(arr1, arr2))
 
print('\nApplying remainder() function:')
print(np.remainder(arr1, arr2))

print('\nApplying power function:')
print(np.power(arr1, 2))


Adding the two arrays:
[[ 5  7]
 [ 9 11]]

Subtracting the two arrays:
[[-5 -5]
 [-5 -5]]

Multiplying the two arrays:
[[ 0  6]
 [14 24]]

Dividing the two arrays:
[[0.         0.16666667]
 [0.28571429 0.375     ]]

Applying mod() function:
[[0 1]
 [2 3]]

Applying remainder() function:
[[0 1]
 [2 3]]

Applying power function:
[[0 1]
 [4 9]]


In [84]:
for i in arr1:
    print (i*2)

[0 2]
[4 6]
