### Linear Algebra

The Linear Algebra module of NumPy (linalg) offers various methods to apply linear algebra on any numpy array.

In [ ]:
import numpy as np 

In [35]:
arr = np.random.randint(1,20,9)
arr = arr.reshape(3,3)
arr

array([[ 6, 10, 15],
       [ 1, 11, 12],
       [11, 12,  4]])

In [36]:
print("Rank of Arr:", np.linalg.matrix_rank(arr))

Rank of Arr: 3


In [37]:
print("\nDeterminant of Arr:", np.linalg.det(arr))


Determinant of Arr: -954.9999999999993


In [38]:
print("\nInverse of A:\n", np.linalg.inv(arr))


Inverse of A:
 [[ 0.10471204 -0.14659686  0.04712042]
 [-0.13403141  0.14764398  0.05968586]
 [ 0.11413613 -0.03979058 -0.05863874]]


In [46]:
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(arr, 100))


Matrix A raised to power 3:
 [[ 1390567387   640076784 -1697835590]
 [ 1909145372 -1871777851 -1223455346]
 [ -757184310  -401668484  2085650331]]


In [49]:
# Scalars
product = np.dot(5, 4)
print("Dot Product of scalar values  : ", product)
 
# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j
 
product = np.dot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product of scalar values  :  20
Dot Product  :  (-7+22j)


In [52]:
ar = np.random.randint(1,20,9)
ar = arr.reshape(3,3)
ar
print(np.matmul(ar, arr))

[[211 350 270]
 [149 275 195]
 [122 290 325]]
